name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main  # or the branch you deploy from

env:
  AZURE_WEBAPP_NAME: node-project-g2c2b3f4a3gefdc0.westeurope-01.azurewebsites.net         # e.g., coffee-shop-web
  AZURE_CONTAINER_REGISTRY: nodetest099988.azurecr.io  # e.g., myacr.azurecr.io
  IMAGE_NAME: coffeesite                          # name of the docker image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: "nodetest099988"
        password: "V+QxStokY9ld0YQpRJbbPRgzqVdROmwcvBP6xvSetx+ACRChHHmD"

    - name: Build and push Docker image
      run: |
        docker build -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest .
        docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest

    - name: Deploy to Azure Web App (Container)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
